# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 50.0
  allowed_goal_duration_margin: 1.0
  allowed_start_tolerance: 1.5
  allowed_goal_tolerance: 1.5
  trajectory_duration_monitoring: false
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - manipulator_controller

  manipulator_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    # action_ns: "follow_joint_trajectory"
    # default: true